<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en-US" xml:lang="en-US"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.41">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Martin Köhler">
<meta name="dcterms.date" content="2025-02-21">

<title>KLayout-PEX Documentation – KLayout-PEX</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-48ffa3e5b9d089919c6712c39e5b00f2.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark-71390cc8b9bae10139428574d3aab2c6.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-57f86f76a34a3b5fcd4725c815234fdf.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark-ebe4cc08c959f78266c1f62ba9a6f235.min.css" rel="prefetch" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">KLayout-PEX</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> <i class="bi bi-house" role="img">
</i> 
<span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../doc/doc.html" aria-current="page"> 
<span class="menu-text">Documentation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../doc/test-reports.html"> 
<span class="menu-text">Test Reports</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../doc/python-coverage.html"> 
<span class="menu-text">🐍 Coverage</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/martinjankoehler/klayout-pex-website" target="_blank"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active" data-toc-expanded="2">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-intro" id="toc-sec-intro" class="nav-link active" data-scroll-target="#sec-intro"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#motivation" id="toc-motivation" class="nav-link" data-scroll-target="#motivation"><span class="header-section-number">1.1</span> Motivation</a></li>
  <li><a href="#acknowledgements" id="toc-acknowledgements" class="nav-link" data-scroll-target="#acknowledgements"><span class="header-section-number">1.2</span> Acknowledgements</a></li>
  <li><a href="#about-klayout-pex" id="toc-about-klayout-pex" class="nav-link" data-scroll-target="#about-klayout-pex"><span class="header-section-number">1.3</span> About KLayout-PEX</a></li>
  <li><a href="#status" id="toc-status" class="nav-link" data-scroll-target="#status"><span class="header-section-number">1.4</span> Status</a></li>
  <li><a href="#sec-intro-installation" id="toc-sec-intro-installation" class="nav-link" data-scroll-target="#sec-intro-installation"><span class="header-section-number">1.5</span> Installation</a>
  <ul class="collapse">
  <li><a href="#option-1-using-iic-osic-tools-docker-image" id="toc-option-1-using-iic-osic-tools-docker-image" class="nav-link" data-scroll-target="#option-1-using-iic-osic-tools-docker-image"><span class="header-section-number">1.5.1</span> Option 1: Using <code>IIC-OSIC-TOOLS</code> Docker Image</a></li>
  <li><a href="#option-2-standalone-installation" id="toc-option-2-standalone-installation" class="nav-link" data-scroll-target="#option-2-standalone-installation"><span class="header-section-number">1.5.2</span> Option 2: Standalone Installation</a></li>
  <li><a href="#sec-intro-meshlab" id="toc-sec-intro-meshlab" class="nav-link" data-scroll-target="#sec-intro-meshlab"><span class="header-section-number">1.5.3</span> Useful tools: <code>meshlab</code></a></li>
  </ul></li>
  </ul></li>
  <li><a href="#first-steps" id="toc-first-steps" class="nav-link" data-scroll-target="#first-steps"><span class="header-section-number">2</span> First Steps</a>
  <ul class="collapse">
  <li><a href="#example-layouts" id="toc-example-layouts" class="nav-link" data-scroll-target="#example-layouts"><span class="header-section-number">2.1</span> Example Layouts</a></li>
  <li><a href="#sec-first-steps-run-fastercap-engine" id="toc-sec-first-steps-run-fastercap-engine" class="nav-link" data-scroll-target="#sec-first-steps-run-fastercap-engine"><span class="header-section-number">2.2</span> Running the <code>KPEX/FasterCap</code> engine</a></li>
  <li><a href="#sec-first-steps-run-magic-engine" id="toc-sec-first-steps-run-magic-engine" class="nav-link" data-scroll-target="#sec-first-steps-run-magic-engine"><span class="header-section-number">2.3</span> Running the <code>KPEX/MAGIC</code> engine</a></li>
  </ul></li>
  <li><a href="#supporting-new-pdks" id="toc-supporting-new-pdks" class="nav-link" data-scroll-target="#supporting-new-pdks"><span class="header-section-number">3</span> Supporting new PDKs</a>
  <ul class="collapse">
  <li><a href="#sec-tech-def" id="toc-sec-tech-def" class="nav-link" data-scroll-target="#sec-tech-def"><span class="header-section-number">3.1</span> Technology Definition Files</a></li>
  <li><a href="#customized-pex-lvs-scripts" id="toc-customized-pex-lvs-scripts" class="nav-link" data-scroll-target="#customized-pex-lvs-scripts"><span class="header-section-number">3.2</span> Customized PEX-“LVS” scripts</a></li>
  </ul></li>
  <li><a href="#kpexfastercap-engine" id="toc-kpexfastercap-engine" class="nav-link" data-scroll-target="#kpexfastercap-engine"><span class="header-section-number">4</span> <code>KPEX/FasterCap</code> Engine</a>
  <ul class="collapse">
  <li><a href="#d-input-geometries" id="toc-d-input-geometries" class="nav-link" data-scroll-target="#d-input-geometries"><span class="header-section-number">4.1</span> 3D Input Geometries</a></li>
  <li><a href="#example-mom-capacitor" id="toc-example-mom-capacitor" class="nav-link" data-scroll-target="#example-mom-capacitor"><span class="header-section-number">4.2</span> Example: MOM Capacitor</a></li>
  <li><a href="#output-maxwell-capacitance-matrix" id="toc-output-maxwell-capacitance-matrix" class="nav-link" data-scroll-target="#output-maxwell-capacitance-matrix"><span class="header-section-number">4.3</span> Output Maxwell Capacitance Matrix</a></li>
  </ul></li>
  <li><a href="#kpexmagic-engine" id="toc-kpexmagic-engine" class="nav-link" data-scroll-target="#kpexmagic-engine"><span class="header-section-number">5</span> <code>KPEX/MAGIC</code> Engine</a>
  <ul class="collapse">
  <li><a href="#sec-magic-cap-types" id="toc-sec-magic-cap-types" class="nav-link" data-scroll-target="#sec-magic-cap-types"><span class="header-section-number">5.1</span> Types of Parasitic Capacitances</a></li>
  <li><a href="#substrate-capacitance" id="toc-substrate-capacitance" class="nav-link" data-scroll-target="#substrate-capacitance"><span class="header-section-number">5.2</span> Substrate Capacitance</a></li>
  <li><a href="#sidewall-capacitance" id="toc-sidewall-capacitance" class="nav-link" data-scroll-target="#sidewall-capacitance"><span class="header-section-number">5.3</span> Sidewall Capacitance</a></li>
  <li><a href="#overlap-capacitance" id="toc-overlap-capacitance" class="nav-link" data-scroll-target="#overlap-capacitance"><span class="header-section-number">5.4</span> Overlap Capacitance</a></li>
  <li><a href="#fringe-capacitance" id="toc-fringe-capacitance" class="nav-link" data-scroll-target="#fringe-capacitance"><span class="header-section-number">5.5</span> Fringe Capacitance</a></li>
  <li><a href="#shielding-effects" id="toc-shielding-effects" class="nav-link" data-scroll-target="#shielding-effects"><span class="header-section-number">5.6</span> Shielding Effects</a></li>
  </ul></li>
  <li><a href="#sec-engine-kpex-2_5D" id="toc-sec-engine-kpex-2_5D" class="nav-link" data-scroll-target="#sec-engine-kpex-2_5D"><span class="header-section-number">6</span> <code>KPEX/2.5D</code> Engine</a></li>
  <li><a href="#sec-test-patterns" id="toc-sec-test-patterns" class="nav-link" data-scroll-target="#sec-test-patterns"><span class="header-section-number">7</span> Comparison KPEX/2.5D with MAGIC</a>
  <ul class="collapse">
  <li><a href="#test-pattern-single_plate_100um_x_100um_li1_over_substrate" id="toc-test-pattern-single_plate_100um_x_100um_li1_over_substrate" class="nav-link" data-scroll-target="#test-pattern-single_plate_100um_x_100um_li1_over_substrate"><span class="header-section-number">7.1</span> Test Pattern <code>single_plate_100um_x_100um_li1_over_substrate</code></a></li>
  <li><a href="#test-pattern-sidewall_20um_length_distance_200nm_li1" id="toc-test-pattern-sidewall_20um_length_distance_200nm_li1" class="nav-link" data-scroll-target="#test-pattern-sidewall_20um_length_distance_200nm_li1"><span class="header-section-number">7.2</span> Test Pattern <code>sidewall_20um_length_distance_200nm_li1</code></a></li>
  <li><a href="#test-pattern-sideoverlap_simple_plates_li1_m1" id="toc-test-pattern-sideoverlap_simple_plates_li1_m1" class="nav-link" data-scroll-target="#test-pattern-sideoverlap_simple_plates_li1_m1"><span class="header-section-number">7.3</span> Test Pattern <code>sideoverlap_simple_plates_li1_m1</code></a></li>
  </ul></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">8</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8.1</span> References</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="doc.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">KLayout-PEX Documentation</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Martin Köhler <a href="mailto:martin.koehler@jku.at" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            <a href="https://www.jku.at/en/institute-for-integrated-circuits-and-quantum-computing">
            Johannes Kepler University
            </a>
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">February 21, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div style="page-break-after: always;"></div>
<section id="sec-intro" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<section id="motivation" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="motivation"><span class="header-section-number">1.1</span> Motivation</h2>
<p>In Electronic Design and Automation (EDA) for Integrated Circuits (ICs), a schematic presents an abstraction in comparison to the layout that will eventually be taped-out and fabricated by the semiconductor foundry.</p>
<p>While in the schematic, a connection between device terminals is seen as an equipotential, the stacked geometries in a specific layout introduce parasitic effects, which can be thought of additional resistors, capacitors (and inductors), not modeled by and missing in the original schematic.</p>
<p>To be able to simulate these effects, a parasitic extraction tool (PEX) is used, to extract a netlist from the layout, which represents the original schematic (created from the layout active and passive elements) augmented with the additional parasitic devices.</p>
</section>
<section id="acknowledgements" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="acknowledgements"><span class="header-section-number">1.2</span> Acknowledgements</h2>
<p>Special thanks to the public funded German project FMD-QNC (16ME0831) <a href="https://www.elektronikforschung.de/projekte/fmd-qnc" class="uri">https://www.elektronikforschung.de/projekte/fmd-qnc</a> for financial support to this work.</p>
</section>
<section id="about-klayout-pex" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="about-klayout-pex"><span class="header-section-number">1.3</span> About KLayout-PEX</h2>
<p><a href="https://klayout.de">KLayout</a> is an open source VLSI layout viewer and editor.</p>
<p><a href="https://pypi.org/project/klayout-pex/">KLayout-PEX</a> (short <code>KPEX</code>) is a PEX tool, well integrated with <code>KLayout</code> by using its API.</p>
<p>There are multiple PEX engines supported, currently:</p>
<ul>
<li><a href="https://www.fastfieldsolvers.com/fastercap.htm">FasterCap</a> integration (field solver engine)</li>
<li><a href="https://opencircuitdesign.com/magic/">MAGIC</a> integration (wrapper calling <code>magic</code>)</li>
<li>Analytical 2.5D engine (parasitic concepts and formulas of MAGIC, implemented using KLayout methods)</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>KPEX <em>tool</em> source code itself is made publicly available on GitHub (<a href="https://github.com/martinjankoehler/klayout-pex">follow this link</a>) and shared under the GPL-3.0 license.</p>
<p>KPEX <em>documentation</em> source code is made publicly available on GitHub (<a href="https://github.com/martinjankoehler/klayout-pex-website">follow this link</a>) and shared under the Apache-2.0 license.</p>
<p>Please feel free to create issues and/or submit pull requests on GitHub to fix errors and omissions!</p>
<p>The production of the tool and this document would be impossible without these (and many more) great open-source software products: <code>KLayout</code>, <code>FasterCap</code>, <code>MAGIC</code>, <code>protobuf</code>, <code>Quarto</code>, <code>Python</code>, <code>ngspice</code>, <code>Numpy</code>, <code>Scipy</code>, <code>Matplotlib</code>, <code>Git</code>, <code>Docker</code>, <code>Ubuntu</code>, <code>Linux</code>…</p>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p>Currently, <code>KPEX</code> is developed as a Python prototype, using the <a href="https://www.klayout.de/doc-qt5/code/">KLayout Python API</a>. This allows for a faster development cycle during the current prototyping phase.</p>
<p>Eventually, critical parts will be re-implemented (in C++, and parallelized), to improve performance. As we’re already using the KLayout API (which is pretty similar between Python, Ruby and C++), this will be relatively straight-forward.</p>
</div>
</div>
</section>
<section id="status" class="level2" data-number="1.4">
<h2 data-number="1.4" class="anchored" data-anchor-id="status"><span class="header-section-number">1.4</span> Status</h2>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>Please keep in mind that this software is early stage, and not yet intended for production use.</p>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 17%">
<col style="width: 58%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Engine</th>
<th style="text-align: left;">PEX Type</th>
<th style="text-align: left;">Status</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>KPEX/MAGIC</code></td>
<td style="text-align: left;"><code>CC</code>, <code>RC</code></td>
<td style="text-align: left;">Usable</td>
<td style="text-align: left;">Wrapper engine, using installed <code>magic</code> tool</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>KPEX/FasterCap</code></td>
<td style="text-align: left;"><code>CC</code></td>
<td style="text-align: left;">Usable, <strong>pending QA</strong></td>
<td style="text-align: left;">Field solver engine using <code>FasterCap</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>KPEX/FastHenry2</code></td>
<td style="text-align: left;"><code>R</code>, <code>L</code></td>
<td style="text-align: left;">Planned</td>
<td style="text-align: left;">Field solver engine using <code>FastHenry2</code></td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>KPEX/2.5D</code></td>
<td style="text-align: left;"><code>CC</code></td>
<td style="text-align: left;"><strong>Under construction</strong></td>
<td style="text-align: left;">Prototype engine implementing MAGIC concepts/formulas with <code>KLayout</code> means</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>KPEX/2.5D</code></td>
<td style="text-align: left;"><code>R</code>, <code>RC</code></td>
<td style="text-align: left;">Planned</td>
<td style="text-align: left;">Prototype engine implementing MAGIC concepts/formulas with <code>KLayout</code> means</td>
</tr>
</tbody>
</table>
</section>
<section id="sec-intro-installation" class="level2" data-number="1.5">
<h2 data-number="1.5" class="anchored" data-anchor-id="sec-intro-installation"><span class="header-section-number">1.5</span> Installation</h2>
<p>Generally, <code>KPEX</code> is deployed using PyPi (Python Package Index), install via:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb1-1"><a href="#cb1-1"></a><span class="ex">pip3</span> install <span class="at">--upgrade</span> klayout-pex</span>
<span id="cb1-2"><a href="#cb1-2"></a></span>
<span id="cb1-3"><a href="#cb1-3"></a><span class="ex">kpex</span> <span class="at">--version</span>   <span class="co"># check the installed version </span></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="ex">kpex</span> <span class="at">--help</span>      <span class="co"># this will help with command line arguments</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As for the dependencies, there are multiple options available.</p>
<section id="option-1-using-iic-osic-tools-docker-image" class="level3" data-number="1.5.1">
<h3 data-number="1.5.1" class="anchored" data-anchor-id="option-1-using-iic-osic-tools-docker-image"><span class="header-section-number">1.5.1</span> Option 1: Using <code>IIC-OSIC-TOOLS</code> Docker Image</h3>
<p>We provide a comprehensive, low entry barrier Docker image that comes pre-installed with most relevant open source ASIC tools, as well as the open PDKs. This is a pre-compiled Docker image which allows to do circuit design on a virtual machine on virtually any type of computing equipment (personal PC, Raspberry Pi, cloud server) on various operating systems (Windows, macOS, Linux).</p>
<p>For further information please look at the <a href="https://hub.docker.com/r/hpretl/iic-osic-tools">Docker Hub page</a> and for detailed instructions at the <a href="https://github.com/iic-jku/IIC-OSIC-TOOLS">IIC-OSIC-TOOLS GitHub page</a>.</p>
<div class="callout callout-style-default callout-warning callout-titled" title="Linux">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Linux
</div>
</div>
<div class="callout-body-container callout-body">
<p>In this document, we assume that users have a basic knowledge of Linux and how to operate it using the terminal (shell). If you are not yet familiar with Linux (which is basically a must when doing integrated circuit design as many tools are only available on Linux), then please check out a Linux introductory course or tutorial online, there are many resources available.</p>
<p>A summary of important Linux shell commands is provided in <a href="https://iic-jku.github.io/analog-circuit-design/#sec-linux-cheatsheet">IIC-JKU Linux Cheatsheet</a>.</p>
</div>
</div>
</section>
<section id="option-2-standalone-installation" class="level3" data-number="1.5.2">
<h3 data-number="1.5.2" class="anchored" data-anchor-id="option-2-standalone-installation"><span class="header-section-number">1.5.2</span> Option 2: Standalone Installation</h3>
<ul>
<li><a href="https://klayout.de">KLayout</a> layout tool:
<ul>
<li>is mandatory for all engines (besides the MAGIC-wrapper)</li>
<li><a href="https://www.klayout.de/build.html">get the latest pre-built package version</a></li>
<li>or <a href="https://www.klayout.de/build.html">follow the build instructions</a></li>
</ul></li>
<li><a href="https://www.fastfieldsolvers.com/fastercap.htm">FasterCap</a> engine:
<ul>
<li>optional, required to run the FasterCap engine</li>
<li>either compile your own version from the <a href="https://github.com/ediloren/FasterCap/">GitHub repository</a></li>
<li>or use precompiled versions available at <a href="https://github.com/martinjankoehler/FasterCap/releases" class="uri">https://github.com/martinjankoehler/FasterCap/releases</a></li>
</ul></li>
<li><a href="https://opencircuitdesign.com/magic/">MAGIC</a>-wrapper engine:
<ul>
<li>optional, required to run the MAGIC-wrapper engine</li>
<li>Follow the <a href="https://github.com/RTimothyEdwards/magic/blob/master/INSTALL">installation instructions</a> at the <a href="https://github.com/RTimothyEdwards/magic/">GitHub repository</a></li>
</ul></li>
<li><a href="https://skywater-pdk.readthedocs.io">Skywater sky130A PDK</a>:
<ul>
<li>optional, for now, KPEX technology specific files are deployed within the <code>klayout-pex</code> Python package</li>
<li><code>pip3 install --upgrade volare</code> (install PDK package manager)</li>
<li><code>volare ls-remote</code> (retrieve available PDK releases
<ul>
<li>for example <code>PRE-RELEASE 0c1df35fd535299ea1ef74d1e9e15dedaeb34c32 (2024.12.11)</code>)</li>
</ul></li>
<li><code>volare enable 0c1df35fd535299ea1ef74d1e9e15dedaeb34c32</code> (install a PDK version)</li>
<li>PDK files now have been installed under <code>$HOME/.volare/sky130A</code></li>
</ul></li>
<li><a href="https://github.com/IHP-GmbH/IHP-Open-PDK">IHP SG13G2 PDK</a>:
<ul>
<li>optional, for now, KPEX technology specific files are deployed within the <code>klayout-pex</code> Python package</li>
<li><code>git clone https://github.com/IHP-GmbH/IHP-Open-PDK</code> (install PDK package manager)</li>
</ul></li>
</ul>
</section>
<section id="sec-intro-meshlab" class="level3" data-number="1.5.3">
<h3 data-number="1.5.3" class="anchored" data-anchor-id="sec-intro-meshlab"><span class="header-section-number">1.5.3</span> Useful tools: <code>meshlab</code></h3>
<p>For previewing generated 3D geometries, representing the input to <code>FasterCap</code>, we recommend installing <a href="https://www.meshlab.net">MeshLab</a>. The generated <code>STL</code>-files are located at <code>output/&lt;design&gt;/Geometries/*.stl</code>.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
</section>
<section id="first-steps" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> First Steps</h1>
<ul>
<li>The command line tool <code>kpex</code> is used to trigger the parasitic extraction flow from the terminal.</li>
<li>Get help calling <code>kpex --help</code>.</li>
</ul>
<section id="example-layouts" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="example-layouts"><span class="header-section-number">2.1</span> Example Layouts</h2>
<p>Example layouts are included in the <code>testdata/designs</code> subdirectory of the KLayout-PEX source code:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb2-1"><a href="#cb2-1"></a><span class="fu">git</span> clone https://github.com/martinjankoehler/klayout-pex.git </span>
<span id="cb2-2"><a href="#cb2-2"></a></span>
<span id="cb2-3"><a href="#cb2-3"></a><span class="co"># for sky130A</span></span>
<span id="cb2-4"><a href="#cb2-4"></a><span class="fu">find</span> testdata/designs/sky130A <span class="at">-name</span> <span class="st">"*.gds.gz"</span></span>
<span id="cb2-5"><a href="#cb2-5"></a></span>
<span id="cb2-6"><a href="#cb2-6"></a><span class="co"># for IHP SG13G2</span></span>
<span id="cb2-7"><a href="#cb2-7"></a><span class="fu">find</span> testdata/designs/ihp_sg13g2 <span class="at">-name</span> <span class="st">"*.gds.gz"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="sec-first-steps-run-fastercap-engine" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-first-steps-run-fastercap-engine"><span class="header-section-number">2.2</span> Running the <code>KPEX/FasterCap</code> engine</h2>
<p>Preconditions:</p>
<ul>
<li><code>klayout-pex</code> was installed, see <a href="#sec-intro-installation" class="quarto-xref">Section&nbsp;1.5</a></li>
<li><code>FasterCap</code> was installed, see <a href="#sec-intro-installation" class="quarto-xref">Section&nbsp;1.5</a></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Normally, devices with SPICE <span class="citation" data-cites="Nagel_1975">(<a href="#ref-Nagel_1975" role="doc-biblioref">Nagel 1975</a>)</span> simulation models (e.g.&nbsp;like MOM-capacitors<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> in the sky130A PDK) are ignored (“blackboxed”) during parasitic extraction.</p>
<p><code>kpex</code> has an option <code>--blacklist n</code> to allow extraction of those devices (whiteboxing), which can be useful during development (during the prototype phase, whiteboxing is actually the default setting, so please use <code>--blacklist y</code> to explicitly configure blackboxing).</p>
</div>
</div>
<p>Let’s try the following:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1"></a><span class="ex">kpex</span> <span class="at">--pdk</span> sky130A <span class="at">--blackbox</span> n <span class="at">--gds</span> <span class="dt">\</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>  testdata/designs/sky130A/<span class="pp">*</span>/cap_vpp_04p4x04p6_l1m1m2_noshield.gds.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>This will report an error that we have not activated one or more engines, and list the available engines:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: left;">Argument</th>
<th style="text-align: left;">Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;"><code>--fastercap</code></td>
<td style="text-align: left;">Run kpex/FasterCap engine</td>
</tr>
<tr class="even">
<td style="text-align: left;"><code>--2.5D</code></td>
<td style="text-align: left;">Run kpex/2.5D engine</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><code>--magic</code></td>
<td style="text-align: left;">Run MAGIC engine</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Now, to run the FasterCap engine (might take a couple of minutes):</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb4-1"><a href="#cb4-1"></a><span class="ex">kpex</span> <span class="at">--pdk</span> sky130A <span class="at">--blackbox</span> n <span class="at">--fastercap</span> <span class="at">--gds</span> <span class="dt">\</span></span>
<span id="cb4-2"><a href="#cb4-2"></a>  testdata/designs/sky130A/<span class="pp">*</span>/cap_vpp_04p4x04p6_l1m1m2_noshield.gds.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Within the output directory (defaults to <code>output</code>), <code>KPEX</code> creates a subdirectory <code>Geometries</code>, containing STL-files that provide a preview of the <code>FasterCap</code> input geometries. Use <code>MeshLab</code> (see <a href="#sec-intro-meshlab" class="quarto-xref">Section&nbsp;1.5.3</a>) to open and preview those files:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb5-1"><a href="#cb5-1"></a><span class="fu">ls</span> <span class="at">-d</span> output/cap_vpp_04<span class="pp">*</span>/Geometries/<span class="pp">*</span>.stl</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Open the <code>*.stl</code> files in <code>MeshLab</code></li>
<li>Use the eye buttons to hide and show each file/mesh</li>
<li>Use the align tool (“A” in the toolbar) to assign different colors</li>
<li>Start by showing only on the conductors (files named <code>cond_*.stl</code>)</li>
<li>Then try showing different dielectrics (files named <code>diel_*.stl</code>), to see how they surround the conductors.</li>
</ul>
<p><img src="figures/meshlab-3D-mom-capacitor.jpg" class="img-fluid" alt="MOM Capacitor 3D Model"></p>
</div>
</div>
<p>In the log file, we see the output of FasterCap including the Maxwell capacitance matrix:</p>
<pre><code>Capacitance matrix is:
Dimension 3 x 3
g1_VSUBS  5.2959e-09 -4.46971e-10 -1.67304e-09
g2_C1  -5.56106e-10 1.5383e-08 -1.47213e-08
g3_C0  -1.69838e-09 -1.48846e-08 1.64502e-08</code></pre>
<p><code>KPEX</code> interprets this matrix and prints a CSV netlist, which can be pasted into a spreadsheet application:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode numberSource csv number-lines code-with-copy"><code class="sourceCode"><span id="cb7-1"><a href="#cb7-1"></a>Device;Net1;Net2;Capacitance [fF]</span>
<span id="cb7-2"><a href="#cb7-2"></a>Cext_0_1;VSUBS;C1;0.5</span>
<span id="cb7-3"><a href="#cb7-3"></a>Cext_0_2;VSUBS;C0;1.69</span>
<span id="cb7-4"><a href="#cb7-4"></a>Cext_1_2;C1;C0;14.8</span>
<span id="cb7-5"><a href="#cb7-5"></a>Cext_1_1;C1;VSUBS;0.08</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>In addition, a SPICE netlist is generated.</p>
</section>
<section id="sec-first-steps-run-magic-engine" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-first-steps-run-magic-engine"><span class="header-section-number">2.3</span> Running the <code>KPEX/MAGIC</code> engine</h2>
<p>Preconditions:</p>
<ul>
<li><code>klayout-pex</code> was installed, see <a href="#sec-intro-installation" class="quarto-xref">Section&nbsp;1.5</a></li>
<li><code>magic</code> was installed, see <a href="#sec-intro-installation" class="quarto-xref">Section&nbsp;1.5</a></li>
</ul>
<p>The magic section of <code>kpex --help</code> describes the arguments and their defaults. Important arguments:</p>
<ul>
<li><code>--magicrc</code>: specify location of the <code>magicrc</code> file</li>
<li><code>--gds</code>: path to the GDS input layout</li>
<li><code>--magic</code>: enable magic engine</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode numberSource bash number-lines code-with-copy"><code class="sourceCode bash"><span id="cb8-1"><a href="#cb8-1"></a><span class="ex">kpex</span> <span class="at">--pdk</span> sky130A <span class="at">--magic</span> <span class="at">--gds</span> <span class="dt">\</span></span>
<span id="cb8-2"><a href="#cb8-2"></a>  testdata/designs/sky130A/<span class="pp">*</span>/cap_vpp_04p4x04p6_l1m1m2_noshield.gds.gz</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="supporting-new-pdks" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Supporting new PDKs</h1>
<p>For every supported PDK, a <code>KPEX</code> technology definition is required, as well as customized PEX-“LVS” scripts.</p>
<section id="sec-tech-def" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="sec-tech-def"><span class="header-section-number">3.1</span> Technology Definition Files</h2>
<p>The <code>KPEX</code> technology definition format uses <a href="https://protobuf.net">Google Protocol Buffers</a>, so there is:</p>
<ul>
<li>formal schema files, defining the structure and data types involved
<ul>
<li><a href="https://github.com/martinjankoehler/klayout-pex/blob/main/protos/tech.proto"><code>protos/tech.proto</code></a>: main schema / entry point, includes the others</li>
<li><a href="https://github.com/martinjankoehler/klayout-pex/blob/main/protos/process_stack.proto"><code>protos/process_stack.proto</code></a>: describes details of the process stack, such as dielectrics and heights of layers</li>
<li><a href="https://github.com/martinjankoehler/klayout-pex/blob/main/protos/process_parasitics.proto"><code>protos/process_parasitics.proto</code></a>: parasitic tables, used to parametrize the 2.5D engine</li>
</ul></li>
<li>multiple concrete instantiations, that adhere to this schema (called <em>messages</em> in the <code>protobuf</code> lingo)
<ul>
<li>in the form of JSON files</li>
<li>Skywater 130A: <code>klayout_pex_protobuf/sky130A_tech.pb.json</code></li>
<li>IHP SG13G2: <code>klayout_pex_protobuf/ihp_sg13g2_tech.pb.json</code></li>
</ul></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>The built-in JSON tech files are programmatically generated during the build process<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Therefore they not part of the repository source code, but of course part of the deployed Python wheels. To review those, look into your Python <code>site-packages</code><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>/<code>klayout_pex_protobuf</code>.</p>
</div>
</div>
</section>
<section id="customized-pex-lvs-scripts" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="customized-pex-lvs-scripts"><span class="header-section-number">3.2</span> Customized PEX-“LVS” scripts</h2>
<p><code>KLayout</code> has built-in support for Layout-Versus-Schematic (LVS) scripts, based on its Ruby API. Customized “LVS” scripts are (“ab”)used in <code>KPEX</code>, not with the intent of comparing Layout-Versus-Schematic, but rather to extract the connectivity/net information for all polygons across multiple layers. The resulting net information is stored in a <code>KLayout LVS Database</code> (“LVSDB”).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/kpex-net-formation.svg" class="img-fluid figure-img"></p>
<figcaption><code>KPEX</code> Net Formation</figcaption>
</figure>
</div>
<p>These customized “LVS” scripts are stored in:</p>
<ul>
<li>Skywater sky130A: <a href="https://github.com/martinjankoehler/klayout-pex/blob/main/pdk/sky130A/libs.tech/kpex/sky130.lvs"><code>pdk/sky130A/libs.tech/kpex/sky130.lvs</code></a></li>
<li>IHP SG13G2: <a href="https://github.com/martinjankoehler/klayout-pex/blob/main/pdk/ihp_sg13g2/libs.tech/kpex/sg13g2.lvs"><code>pdk/ihp_sg13gs/libs.tech/kpex/sg13g2.lvs</code></a></li>
</ul>
<p>What’s specific about this customization:</p>
<ul>
<li>Layers names must be assigned, using <a href="https://www.klayout.de/doc-qt5/about/drc_ref_netter.html#name">KLayout’s <code>(name(layer, name))</code> function</a></li>
<li>MOM<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a> capacitors, MIM<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a> capacitors and resistors should be extracted to separate layers, to enable blackboxing / whiteboxing.</li>
</ul>
<p>The layer names in the script must correspond with the names configured in the tech JSON file.</p>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="kpexfastercap-engine" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> <code>KPEX/FasterCap</code> Engine</h1>
<p><code>FasterCap</code> is a 3D and 2D parallel capacitance field solver, inspired by <code>FastCap2</code>. <a href="https://www.fastfieldsolvers.com/fastercap.htm" class="uri">https://www.fastfieldsolvers.com/fastercap.htm</a></p>
<p>Starting from an input layout (e.g.&nbsp;GDS file) and a process stack-up (part of the <a href="#sec-tech-def" class="quarto-xref">Section&nbsp;3.1</a>), <code>KPEX</code> creates input geometries for <code>FasterCap</code>. After running <code>FasterCap</code>, the Maxwell capacitance matrix is parsed and interpreted to obtain the parasitic capacitances.</p>
<p>See <a href="#sec-first-steps-run-fastercap-engine" class="quarto-xref">Section&nbsp;2.2</a> to get started with a first extraction example.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/kpex-engine-fastercap-overview.svg" class="img-fluid figure-img"></p>
<figcaption><code>KPEX/FasterCap</code> Engine</figcaption>
</figure>
</div>
<section id="d-input-geometries" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="d-input-geometries"><span class="header-section-number">4.1</span> 3D Input Geometries</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fastercap-input-geometry-3D-part1.svg" class="img-fluid figure-img"></p>
<figcaption><code>FasterCap</code> 3D Input: File System Overview</figcaption>
</figure>
</div>
<p>The <code>FasterCap</code> input files and their format is documented in <span class="citation" data-cites="fastfieldsolvers-fastercap-manual-chm">(<a href="#ref-fastfieldsolvers-fastercap-manual-chm" role="doc-biblioref">Di Lorenzo 2019</a>)</span>, a PDF version of the Windows-specific <code>*.chm</code> file is available at <a href="https://github.com/martinjankoehler/FasterCap/tree/master/doc/pdf" class="uri">https://github.com/martinjankoehler/FasterCap/tree/master/doc/pdf</a>.</p>
<p><code>KPEX</code> generates 3D input geometries:</p>
<ul>
<li><code>*.lst</code> file: Main input file
<ul>
<li>defines dielectric instances</li>
<li>defines conductor instances</li>
<li>each instance refers to a <code>*.geo</code> file</li>
</ul></li>
<li><code>*.geo</code> files: Defines single geometry
<ul>
<li>defines shapes (e.g.&nbsp;triangles)</li>
<li>Each shape has a reference point to define inside/outsides</li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fastercap-input-geometry-3D-part2.svg" class="img-fluid figure-img"></p>
<figcaption><code>FasterCap</code> 3D Input: File Format</figcaption>
</figure>
</div>
</section>
<section id="example-mom-capacitor" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="example-mom-capacitor"><span class="header-section-number">4.2</span> Example: MOM Capacitor</h2>
<div id="fig-fastercap-mom-example" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastercap-mom-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/mom-capacitor-gds.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>MOM Capacitor: GDS Layout</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/mom-capacitor-3D.jpg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>MOM Capacitor: <code>MeshLab</code> 3D Preview</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastercap-mom-example-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: MOM Capacitor
</figcaption>
</figure>
</div>
<p><a href="#fig-fastercap-mom-example" class="quarto-xref">Figure&nbsp;1</a> depicts the MOM capacitor example of a from <a href="#sec-first-steps-run-fastercap-engine" class="quarto-xref">Section&nbsp;2.2</a>).</p>
<p>The corresponding schematic representation of <a href="#fig-fastercap-maxwell-capacitance-matrix-schematic" class="quarto-xref">Figure&nbsp;2</a> contains 3 conductors (<span class="math inline">\(N_1\)</span>, <span class="math inline">\(N_2\)</span> and <span class="math inline">\(N_3\)</span>), and coupling capacitances:</p>
<ul>
<li>Capacitances between conductors: <span class="math inline">\(C_{ij} \text{ where } i \ne j\)</span>
<ul>
<li><span class="math inline">\(C_{23}\)</span> is the capacitance “intended” by the MOM designer</li>
</ul></li>
<li>Capacitances between conductors and ground: <span class="math inline">\(C_{ii}\)</span></li>
</ul>
<div id="cell-fig-fastercap-maxwell-capacitance-matrix-schematic" class="cell" data-execution_count="1">
<div class="cell-output cell-output-display">
<div id="fig-fastercap-maxwell-capacitance-matrix-schematic" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-fastercap-maxwell-capacitance-matrix-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="doc_files/figure-html/fig-fastercap-maxwell-capacitance-matrix-schematic-output-1.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-fastercap-maxwell-capacitance-matrix-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Schematic representation of the MOM capacitor.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="output-maxwell-capacitance-matrix" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="output-maxwell-capacitance-matrix"><span class="header-section-number">4.3</span> Output Maxwell Capacitance Matrix</h2>
<p>A Maxwell capacitance matrix <span class="citation" data-cites="Maxwell_1873">(<a href="#ref-Maxwell_1873" role="doc-biblioref">Maxwell 1873</a>)</span> provides the relation between voltages on a set of conductors and the charges on these conductors, as described by the <code>FasterCap</code> author in the white paper <span class="citation" data-cites="fastfieldsolvers-maxwell-capacitance-matrix">(<a href="#ref-fastfieldsolvers-maxwell-capacitance-matrix" role="doc-biblioref">Di Lorenzo 2023</a>)</span>.</p>
<p><code>FasterCap</code> log output prints the Maxwell capacitance matrix (one for each iteration/refinement).</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fastercap-maxwell-capacitance-matrix-log.svg" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption><code>FasterCap</code> Log Output: Maxwell Capacitance Matrix</figcaption>
</figure>
</div>
<ul>
<li>Matrix Properties:
<ul>
<li>Scaling: units have to be divided by <span class="math inline">\(10^{-6}\)</span></li>
<li>rows and columns are the same (list of net names)</li>
<li>Row Cells:
<ul>
<li>off diagonals cells contains the coupling between row/col nets (times <span class="math inline">\(-1\)</span>)</li>
<li>diagonal cells contains the sum of the absolute values of all other cells in the row</li>
</ul></li>
<li>Matrix Symmetry:
<ul>
<li>in theory (ideal world), the matrix would be symmetric</li>
<li>in practice it’s not<br>
</li>
<li>therefore <code>FastCap2</code> did average the off-diagonals</li>
<li><code>FasterCap</code> does not average, so it’s done as part of <code>KPEX</code></li>
</ul></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/fastercap-maxwell-capacitance-matrix-interpretation.svg" class="img-fluid figure-img"></p>
<figcaption><code>FasterCap</code> Maxwell Capacitance Matrix: Interpretation</figcaption>
</figure>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="kpexmagic-engine" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> <code>KPEX/MAGIC</code> Engine</h1>
<p>This engine is merely just a wrapper around <code>magic</code>, which prepares a TCL script that opens the layout file and starts MAGIC’s PEX flow. See <a href="#sec-first-steps-run-magic-engine" class="quarto-xref">Section&nbsp;2.3</a> to get started with a first extraction example.</p>
<p>The following chapter will illustrate concepts of the parasitic extraction done in <code>MAGIC</code>, also motivated by the fact that the engine in <a href="#sec-engine-kpex-2_5D" class="quarto-xref">Section&nbsp;6</a> will be based on those. Major parts of this illustration, the figures and concepts are based on work done by <code>MAGIC</code> maintainer Tim Edwards, especially his talk from FSiC conference 2022 <span class="citation" data-cites="edwards-2022-fsic-talk">(<a href="#ref-edwards-2022-fsic-talk" role="doc-biblioref">Edwards 2022</a>)</span> and a (conceptual follow-up) ChipsAlliance meeting on April 4, 2023, see <span class="citation" data-cites="edwards-2023-chipsalliance-talk-video">(<a href="#ref-edwards-2023-chipsalliance-talk-video" role="doc-biblioref">Edwards 2023b</a>)</span> and <span class="citation" data-cites="edwards-2023-chipsalliance-talk-slides">(<a href="#ref-edwards-2023-chipsalliance-talk-slides" role="doc-biblioref">Edwards 2023a</a>)</span>. In addition, code review and debugging of the MAGIC codebase was performed.</p>
<section id="sec-magic-cap-types" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="sec-magic-cap-types"><span class="header-section-number">5.1</span> Types of Parasitic Capacitances</h2>
<p>MAGIC models multiple types of capacitances:</p>
<ul>
<li><em>Substrate Overlap:</em> Overlap area of a metal with the substrate</li>
<li><em>Substrate Fringing:</em> Sidewall of a metal fringes out to substrate</li>
<li><em>Sidewall Capacitance:</em> Coupling between adjacent sidewalls on the same layer</li>
<li><em>Overlap Capacitance:</em> Overlap on different metal layers</li>
<li><em>Fringe Capacitance (“Side Overlap”):</em> Sidewall of a metal fringes out other metal layers</li>
</ul>
</section>
<section id="substrate-capacitance" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="substrate-capacitance"><span class="header-section-number">5.2</span> Substrate Capacitance</h2>
<p><img src="figures/magic_cap_type_-_substrate.svg" class="img-fluid" style="width:50.0%"></p>
<ul>
<li><p>Overlapping area: <span class="math display">\[
C_{area} = \frac{\epsilon_{si} * K}{d} * \text{area} \,\,\,\,\,\,\, \left[ \frac{F}{\mu m^2} * \mu m^2\right]
\]</span></p></li>
<li><p>Fringe (“Perimeter”): <span class="math display">\[
C_{fringe\,to\,substrate} = \text{perimeter} * C_{perim} = (2l + 2w)*C_{perim}
\]</span></p></li>
<li><p>Coefficients like <span class="math inline">\(C_{perim}\)</span> are part of the tech files (Parasitic Tables)</p></li>
</ul>
</section>
<section id="sidewall-capacitance" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="sidewall-capacitance"><span class="header-section-number">5.3</span> Sidewall Capacitance</h2>
<p><img src="figures/magic_cap_type_-_sidewall.svg" class="img-fluid" style="width:65.0%"></p>
<p><span class="math display">\[
C_{sidewall} = \frac{\epsilon_{si} * K}{s} * \text{sidewall area}  \,\,\,\,\,\,\, \left[ \frac{F}{\mu m^2} * \mu m^2\right]
\]</span> <span class="math display">\[
\,\,\,\,\,\,\,\,\,\,= \frac{\epsilon_{si} * K}{s} * t * l  \,\,\,\,\,\,\, \left[ \frac{F}{\mu m^2} * \mu m * \mu m\right]
\]</span> <span class="math display">\[
C_{sidewall} = \frac{C_{sidewall\,coeff}}{s} * l \,\,\,\,\,\,\, \left[ \frac{F}{\mu m} * \mu m\right]
\]</span></p>
<div class="{{.callout-note}}">
<ul>
<li>Coefficients are part of the tech files (Parasitic Tables)</li>
<li>Layer thickness <span class="math inline">\(t\)</span> is normally multiplied into the coefficient</li>
<li>Foundry tables give constant coefficient referenced to <span class="math inline">\(s = 1\)</span></li>
</ul>
</div>
</section>
<section id="overlap-capacitance" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="overlap-capacitance"><span class="header-section-number">5.4</span> Overlap Capacitance</h2>
<ul>
<li>Overlapping area: <span class="math display">\[
C_{area} = \frac{\epsilon_{si} * K}{d} * \text{area} \,\,\,\,\,\,\, \left[ \frac{F}{\mu m^2} * \mu m^2\right]
\]</span></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_overlap.svg" class="img-fluid figure-img" style="width:30.0%"></p>
<figcaption>Overlap Capacitance</figcaption>
</figure>
</div>
</section>
<section id="fringe-capacitance" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="fringe-capacitance"><span class="header-section-number">5.5</span> Fringe Capacitance</h2>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_fringe_3D.svg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Fringe Capacitance: Overlapping (1)</figcaption>
</figure>
</div>
<ul>
<li>Causing sidewall (its bottom edge depicted red)</li>
<li>Assume: Field is bounded by fringe halo (e.g.&nbsp;<span class="math inline">\(8\, \mu m\)</span> away from edge)</li>
<li>Fractions of fringe goes to metal1 or substrate</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_fringe_mom.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Fringe Capacitance: Overlapping (2)</figcaption>
</figure>
</div>
<ul>
<li>Multiplier <span class="math inline">\(\alpha\)</span> (comes from tech files: overlap table)
<ul>
<li>determines how quickly fringe capacitance drops with increasing distance</li>
<li><span class="math inline">\(\alpha\)</span> is related to distance <span class="math inline">\(d\)</span>￼ between layers</li>
<li><span class="math inline">\(\alpha\)</span> is proportional to <span class="math inline">\(C_{overlap_{metal1 \leftrightarrow metal2}}= \frac{\epsilon_{si} * K}{d} * \text{area}\)</span><br>
(for fixed value of area <span class="math inline">\(1\, \mu m^2\)</span>) <!-- Markdown NOTE: to force the last list item two separate lines, I've added 2 blanks at the end of the first line  --></li>
</ul></li>
<li>Fringe Fractions:
<ul>
<li><span class="math inline">\(\text{frac}_{metal1} = \tfrac{2}{\pi} * \text{atan}(\alpha_{metal2 \rightarrow metal1}*x)\)</span></li>
<li><span class="math inline">\(\text{frac}_{sub} = \tfrac{2}{\pi} * \text{atan}(\alpha_{metal2 \rightarrow sub}*(\text{halo}-x))\)</span></li>
<li><span class="math inline">\(\tfrac{2}{\pi}\)</span> is multiplied because of scaling to interval <span class="math inline">\([0.0,\,1.0]\)</span>, as￼<span class="math inline">\(\text{atan}(\infty)=\tfrac{\pi}{2}\)</span></li>
</ul></li>
<li>Overlap capacitance:
<ul>
<li><span class="math inline">\(C_{overlap} = \frac{\epsilon_{si} * K}{d} * \text{area} \,\,\,\,\,\,\,\,(\text{with area}=1 \mu m^2)\)</span></li>
</ul></li>
<li>Coupling capacitance <span class="math inline">\(metal1 \leftrightarrow metal2\)</span>:
<ul>
<li><span class="math inline">\(\alpha_{metal1 \leftrightarrow metal2} = \alpha_{scalefac} * C_{overlap_{metal1 \leftrightarrow metal2}}\)</span></li>
<li><span class="math inline">\(\text{frac}_{metal1} = \tfrac{2}{\pi} * \text{atan}(\alpha_{metal1 \leftrightarrow metal2}*x)\)</span></li>
<li><span class="math inline">\(\text{effective length} = \text{edge length} * \text{frac}_{metal1}\)</span></li>
<li><span class="math inline">\(C_{fringe_{metal2 \rightarrow metal1}} = \text{effective length} * C_{sideoverlap_{metal2 \rightarrow metal1}}\)</span></li>
</ul></li>
<li>Coupling capacitance <span class="math inline">\(metal1 \leftrightarrow sub\)</span>:
<ul>
<li><span class="math inline">\(\alpha_{metal1 \leftrightarrow sub} = \alpha_{scalefac} * C_{overlap_{metal1 \leftrightarrow sub}}\)</span></li>
<li><span class="math inline">\(\text{frac}_{sub} = \tfrac{2}{\pi} * \text{atan}(\alpha_{metal1 \leftrightarrow sub}*(\text{halo}-x))\)</span></li>
<li><span class="math inline">\(\text{effective length} = \text{edge length} * \text{frac}_{sub}\)</span></li>
<li><span class="math inline">\(C_{fringe_{metal2 \rightarrow sub}} = \text{effective length} * C_{sideoverlap_{metal2 \rightarrow sub}}\)</span></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_fringe_3D_-_non_overlapping.svg" class="img-fluid figure-img" style="width:50.0%"></p>
<figcaption>Fringe Capacitance: Non Overlapping (1)</figcaption>
</figure>
</div>
<ul>
<li>Partial side overlap
<ul>
<li>In case there is only a partial side overlap, the non-existing near fraction is subtracted from the far fraction</li>
<li><span class="math inline">\(metal1\)</span> wire is offset, starts at <span class="math inline">\(x_{near}\)</span></li>
<li><span class="math inline">\(metal1\)</span> ends at <span class="math inline">\(x_{far}\)</span></li>
</ul></li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_fringe_mom_-_non_overlapping.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption>Fringe Capacitance: Non Overlapping (2)</figcaption>
</figure>
</div>
<ul>
<li><span class="math inline">\(\text{frac}_{near} = \tfrac{2}{\pi} * \text{atan}(\alpha*x_{near})\)</span></li>
<li><span class="math inline">\(\text{frac}_{far} = \tfrac{2}{\pi} * \text{atan}(\alpha*x_{far})\)</span></li>
<li><span class="math inline">\(\text{frac} = \text{frac}_{far}-\text{frac}_{near}\)</span></li>
</ul>
</section>
<section id="shielding-effects" class="level2" data-number="5.6">
<h2 data-number="5.6" class="anchored" data-anchor-id="shielding-effects"><span class="header-section-number">5.6</span> Shielding Effects</h2>
<div id="tbl-magic-cap-shielding-effects" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-magic-cap-shielding-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Shielding effects
</figcaption>
<div aria-describedby="tbl-magic-cap-shielding-effects-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 23%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th><strong>Type</strong></th>
<th colspan="3"><strong>Shielding</strong></th>
</tr>
<tr class="even">
<th></th>
<th><strong>To Substrate</strong></th>
<th><strong>Between layers</strong></th>
<th><strong>On same layer</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overlap shielding</td>
<td>✔</td>
<td>✔</td>
<td>✘</td>
</tr>
<tr class="even">
<td>Sidewall shielding</td>
<td>✘</td>
<td>✘</td>
<td>✔</td>
</tr>
<tr class="odd">
<td>Lateral fringe shielding</td>
<td>✘</td>
<td>✔</td>
<td>✔</td>
</tr>
<tr class="even">
<td>Vertical fringe shielding</td>
<td>✔</td>
<td>✔</td>
<td>✘</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="fig-magic-cap-shielding" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-magic-cap-shielding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_overlap_shielding.svg" class="img-fluid figure-img" style="width:60.0%"></p>
<figcaption>Overlap shielding</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_sidewall_shielding.svg" class="img-fluid figure-img"></p>
<figcaption>Sidewall shielding</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_lateral_fringe_shielding.svg" class="img-fluid figure-img"></p>
<figcaption>Lateral fringe shielding (1/2)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/magic_cap_type_-_vertical_fringe_shielding.svg" class="img-fluid figure-img"></p>
<figcaption>Vertical fringe shielding</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-magic-cap-shielding-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Shielding Effects
</figcaption>
</figure>
</div>
<p>Note, given an analyzed sidewall (edge in 2D), lateral fringe shielding</p>
<ul>
<li>is caused by opposing shapes on the same layer
<ul>
<li>even by the same polygon</li>
<li>by other polygons (same net)</li>
<li>by other polygons (different net) — this is what we also look at when analyzing sidewall coupling</li>
</ul></li>
<li>will shield the fringing to the lower layers, i.e.&nbsp;in <a href="#fig-lateral-fringe-shielding-2" class="quarto-xref">Figure&nbsp;4</a> the coupling between the two shapes is the same in the above and below cases</li>
</ul>
<div id="fig-lateral-fringe-shielding-2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lateral-fringe-shielding-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/magic_cap_type_-_lateral_fringe_shielding2.svg" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lateral-fringe-shielding-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Lateral fringe shielding (2/2)
</figcaption>
</figure>
</div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="sec-engine-kpex-2_5D" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> <code>KPEX/2.5D</code> Engine</h1>
<p>Field solvers are precise, yet slow, they are useful to obtain a golden reference.</p>
<p>For most use cases, a faster engine is desirable-. <code>KPEX/MAGIC</code> is such an engine, but the <code>MAGIC</code> code is tightly coupled with the database, layer/via design choices, and user interface of <code>MAGIC</code>. For example, it runs single-threaded.</p>
<p>Therefore, the <code>KPEX</code> 2.5D Engine intends to implement the concepts and formulas of <code>MAGIC</code> (see <a href="#sec-magic-cap-types" class="quarto-xref">Section&nbsp;5.1</a>), but in a way that is best suited to the <code>KLayout</code> API.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/kpex-engine-2.5D-overview.svg" class="img-fluid figure-img"></p>
<figcaption><code>KPEX</code> 2.5D Engine</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Caution
</div>
</div>
<div class="callout-body-container callout-body">
<p><strong>This section is under heavy construction!</strong></p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="figures/under-construction.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:50.0%" alt="Under heavy construction"></p>
</figure>
</div>
</div>
</div>
<div style="page-break-after: always;"></div>
</section>
<section id="sec-test-patterns" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Comparison KPEX/2.5D with MAGIC</h1>
<p>The initial goal of <code>KPEX/2.5D</code> is to basically come up with the same results as <code>KPEX/MAGIC</code>.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notes about this comparison:</p>
<ul>
<li>Version <code>Magic 8.3 rev 486</code> is used, but augmented with debug logging<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, which will be shown and discussed for each example.</li>
<li><code>KPEX/MAGIC</code> halo is set to <code>--magic_halo=100000</code>
<ul>
<li>NOTE: the screenshots however were created with <code>--magic_halo=8</code> to give better illustrations</li>
</ul></li>
<li><code>KPEX/2.5D</code> halo is set to <code>--halo=100000</code></li>
</ul>
</div>
</div>
<section id="test-pattern-single_plate_100um_x_100um_li1_over_substrate" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="test-pattern-single_plate_100um_x_100um_li1_over_substrate"><span class="header-section-number">7.1</span> Test Pattern <code>single_plate_100um_x_100um_li1_over_substrate</code></h2>
<p>GDS: <a href="https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/single_plate_100um_x_100um_li1_over_substrate.gds.gz" class="uri">https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/single_plate_100um_x_100um_li1_over_substrate.gds.gz</a></p>
<div id="cell-single_plate_100um_x_100um_li1_over_substrate_-_overlap" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display" data-execution_count="2">
<div id="single_plate_100um_x_100um_li1_over_substrate_-_overlap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/single_plate_100um_x_100um_li1_over_substrate_-_overlap-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Overlap capacitance li1 to substrate.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Overlap Capacitances</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overlap</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">369.9</td>
<td style="text-align: right;">369.9</td>
<td style="text-align: right;">4</td>
</tr>
</tbody>
</table>
<div id="cell-single_plate_100um_x_100um_li1_over_substrate_-_perimeter" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display" data-execution_count="3">
<div id="single_plate_100um_x_100um_li1_over_substrate_-_perimeter" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/single_plate_100um_x_100um_li1_over_substrate_-_perimeter-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Perimeter (fringe) capacitance li1 to substrate.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>Fringe (left)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Fringe (right)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Fringe (bottom)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">4.07</td>
<td style="text-align: right;">8</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb9"><pre class="sourceCode numberSource {csv} number-lines code-with-copy"><code class="sourceCode"><span id="cb9-1"><a href="#cb9-1"></a>Magic 8.3 revision 486 - Compiled on `date`.</span>
<span id="cb9-2"><a href="#cb9-2"></a>----------------------------------------------------</span>
<span id="cb9-3"><a href="#cb9-3"></a></span>
<span id="cb9-4"><a href="#cb9-4"></a>CapDebug (extNodeAreaFunc/Area) layer li(90), net li_0_0#, area=400000000 (10000 µm^2) nreg_cap += 369.9 fF</span>
<span id="cb9-5"><a href="#cb9-5"></a>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer li(90), net li_0_0#, length=20000 (100 µm), nreg_cap += 4.07 fF (now nreg_cap = 373.97 fF)</span>
<span id="cb9-6"><a href="#cb9-6"></a>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer li(90), net li_0_0#, length=20000 (100 µm), nreg_cap += 4.07 fF (now nreg_cap = 378.04 fF)</span>
<span id="cb9-7"><a href="#cb9-7"></a>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer li(90), net li_0_0#, length=20000 (100 µm), nreg_cap += 4.07 fF (now nreg_cap = 382.11 fF)</span>
<span id="cb9-8"><a href="#cb9-8"></a>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer li(90), net li_0_0#, length=20000 (100 µm), nreg_cap += 4.07 fF (now nreg_cap = 386.18 fF)</span>
<span id="cb9-9"><a href="#cb9-9"></a>CapDebug (extSetResist): li_0_0# area=400000000 (10000 µm^2) perim=80000 (400 µm)</span>
<span id="cb9-10"><a href="#cb9-10"></a>CapDebug ---</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="test-pattern-sidewall_20um_length_distance_200nm_li1" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="test-pattern-sidewall_20um_length_distance_200nm_li1"><span class="header-section-number">7.2</span> Test Pattern <code>sidewall_20um_length_distance_200nm_li1</code></h2>
<p>GDS: <a href="https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/sidewall_20um_length_distance_200nm_li1.gds.gz" class="uri">https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/sidewall_20um_length_distance_200nm_li1.gds.gz</a></p>
<div id="cell-sidewall_20um_length_distance_200nm_li1_-_overlap" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display" data-execution_count="4">
<div id="sidewall_20um_length_distance_200nm_li1_-_overlap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sidewall_20um_length_distance_200nm_li1_-_overlap-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Overlap capacitance of nets on li1.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Overlap Capacitances</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overlap</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.7398</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td>Overlap</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.7398</td>
<td style="text-align: right;">0.74</td>
<td style="text-align: right;">11</td>
</tr>
</tbody>
</table>
<div id="cell-sidewall_20um_length_distance_200nm_li1_-_sidewall" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display" data-execution_count="5">
<div id="sidewall_20um_length_distance_200nm_li1_-_sidewall" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sidewall_20um_length_distance_200nm_li1_-_sidewall-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Sidewall capacitance between nets A and B on li1.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Sidewall Capacitances</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 9%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 21%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer</th>
<th style="text-align: center;">Net1</th>
<th style="text-align: right;">Net2</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sidewall</td>
<td style="text-align: right;">li1</td>
<td style="text-align: center;">A</td>
<td style="text-align: right;">B</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td>Sidewall</td>
<td style="text-align: right;">li1</td>
<td style="text-align: center;">B</td>
<td style="text-align: right;">A</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">0.75</td>
<td style="text-align: right;">21</td>
</tr>
</tbody>
</table>
<div id="cell-sidewall_20um_length_distance_200nm_li1_-_fringe_A" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display" data-execution_count="6">
<div id="sidewall_20um_length_distance_200nm_li1_-_fringe_a" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sidewall_20um_length_distance_200nm_li1_-_fringe_a-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Fringe capacitance between net A and substrate.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Fringe Capacitances between nets A, B on li1 and substrate</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>Fringe (left)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.0407</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td>Fringe (bottom)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Fringe (bottom)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">-0.7379</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td>Fringe (right)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">A</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.0407</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="even">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">0.076</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">-0.7379</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td>Fringe (left)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.0407</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="odd">
<td>Fringe (bottom)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">0.814</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td>Fringe (right)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">B</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.0407</td>
<td style="text-align: right;">0.041</td>
<td style="text-align: right;">15</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb10"><pre class="sourceCode numberSource {csv} number-lines code-with-copy"><code class="sourceCode"><span id="cb10-1"><a href="#cb10-1"></a>Magic 8.3 revision 486 - Compiled on `date`.</span>
<span id="cb10-2"><a href="#cb10-2"></a>----------------------------------------------------</span>
<span id="cb10-3"><a href="#cb10-3"></a></span>
<span id="cb10-4"><a href="#cb10-4"></a>CapDebug (extNodeAreaFunc/Area) layer li(90), net li_0_240#, area=800000 (20 µm^2) nreg_cap += 0.7398 fF</span>
<span id="cb10-5"><a href="#cb10-5"></a>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer li(90), net li_0_240#, length=4000 (20 µm), nreg_cap += 0.814 fF (now nreg_cap = 1.5538 fF)</span>
<span id="cb10-6"><a href="#cb10-6"></a>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer li(90), net li_0_240#, length=200 (1 µm), nreg_cap += 0.0407 fF (now nreg_cap = 1.5945 fF)</span>
<span id="cb10-7"><a href="#cb10-7"></a>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer li(90), net li_0_240#, length=4000 (20 µm), nreg_cap += 0.814 fF (now nreg_cap = 2.4085 fF)</span>
<span id="cb10-8"><a href="#cb10-8"></a>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer li(90), net li_0_240#, length=200 (1 µm), nreg_cap += 0.0407 fF (now nreg_cap = 2.4492 fF)</span>
<span id="cb10-9"><a href="#cb10-9"></a>CapDebug (extSetResist): li_0_240# area=800000 (20 µm^2) perim=8400 (42 µm)</span>
<span id="cb10-10"><a href="#cb10-10"></a>CapDebug ---</span>
<span id="cb10-11"><a href="#cb10-11"></a>CapDebug (extNodeAreaFunc/Area) layer li(90), net li_0_0#, area=800000 (20 µm^2) nreg_cap += 0.7398 fF</span>
<span id="cb10-12"><a href="#cb10-12"></a>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer li(90), net li_0_0#, length=4000 (20 µm), nreg_cap += 0.814 fF (now nreg_cap = 1.5538 fF)</span>
<span id="cb10-13"><a href="#cb10-13"></a>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer li(90), net li_0_0#, length=200 (1 µm), nreg_cap += 0.0407 fF (now nreg_cap = 1.5945 fF)</span>
<span id="cb10-14"><a href="#cb10-14"></a>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer li(90), net li_0_0#, length=4000 (20 µm), nreg_cap += 0.814 fF (now nreg_cap = 2.4085 fF)</span>
<span id="cb10-15"><a href="#cb10-15"></a>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer li(90), net li_0_0#, length=200 (1 µm), nreg_cap += 0.0407 fF (now nreg_cap = 2.4492 fF)</span>
<span id="cb10-16"><a href="#cb10-16"></a>CapDebug (extSetResist): li_0_0# area=800000 (20 µm^2) perim=8400 (42 µm)</span>
<span id="cb10-17"><a href="#cb10-17"></a>CapDebug ---</span>
<span id="cb10-18"><a href="#cb10-18"></a>CapDebug (sidewall): A-B (layer li), overlap=4000 (20 µm), sep=40 (0.2 µm), e-&gt;ec_cap=12.75 (0.0255 fF), e-&gt;ec_offset=28 (0.14 µm), delta += 0.75 fF …  now is 0.75 fF</span>
<span id="cb10-19"><a href="#cb10-19"></a>CapDebug (obsolete_fringe (blocked)): A -= 0.737881 fF …    now A == 1.711319 fF</span>
<span id="cb10-20"><a href="#cb10-20"></a>    overlapMult=0.003699 (3.699 aF/µm^2) dnear=40 (0.2 µm), snear=0.0935129 (0.000467564 µm), perimCap[90][0]=0.2035 (40.7 /µm), length=4000 (20 µm)</span>
<span id="cb10-21"><a href="#cb10-21"></a>CapDebug (sidewall): A-B (layer li), overlap=4000 (20 µm), sep=40 (0.2 µm), e-&gt;ec_cap=12.75 (0.0255 fF), e-&gt;ec_offset=28 (0.14 µm), delta += 0.75 fF …  now is 1.5 fF</span>
<span id="cb10-22"><a href="#cb10-22"></a>CapDebug (obsolete_fringe (blocked)): B -= 0.737881 fF …    now B == 1.711319 fF</span>
<span id="cb10-23"><a href="#cb10-23"></a>    overlapMult=0.003699 (3.699 aF/µm^2) dnear=40 (0.2 µm), snear=0.0935129 (0.000467564 µm), perimCap[90][0]=0.2035 (40.7 /µm), length=4000 (20 µm)</span>
<span id="cb10-24"><a href="#cb10-24"></a>exttospice finished.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="test-pattern-sideoverlap_simple_plates_li1_m1" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="test-pattern-sideoverlap_simple_plates_li1_m1"><span class="header-section-number">7.3</span> Test Pattern <code>sideoverlap_simple_plates_li1_m1</code></h2>
<p>GDS: <a href="https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/sideoverlap_simple_plates_li1_m1.gds.gz" class="uri">https://github.com/martinjankoehler/klayout-pex/blob/main/testdata/designs/sky130A/test_patterns/sideoverlap_simple_plates_li1_m1.gds.gz</a></p>
<div id="cell-sideoverlap_simple_plates_li1_m1_-_overlap" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display" data-execution_count="7">
<div id="sideoverlap_simple_plates_li1_m1_-_overlap" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sideoverlap_simple_plates_li1_m1_-_overlap-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Overlap capacitances to substrate.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Overlap Capacitances</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 15%">
<col style="width: 12%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Overlap</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">3.699</td>
<td style="text-align: right;">3.7</td>
<td style="text-align: right;">7</td>
</tr>
<tr class="even">
<td>Overlap</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">232.02</td>
<td style="text-align: right;">232.02</td>
<td style="text-align: right;">15</td>
</tr>
</tbody>
</table>
<div id="cell-sideoverlap_simple_plates_li1_m1_-_fringe_li1_substrate" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display" data-execution_count="8">
<div id="sideoverlap_simple_plates_li1_m1_-_fringe_li1_substrate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sideoverlap_simple_plates_li1_m1_-_fringe_li1_substrate-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Fringe capacitances li1 to substrate.</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-sideoverlap_simple_plates_li1_m1_-_fringe_m1_substrate" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display" data-execution_count="9">
<div id="sideoverlap_simple_plates_li1_m1_-_fringe_m1_substrate" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sideoverlap_simple_plates_li1_m1_-_fringe_m1_substrate-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Fringe capacitances met1 to substrate.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Fringe Capacitances between metals and substrate</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">2.035</td>
<td style="text-align: right;">2.035</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="even">
<td>Fringe (bottom)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">2.035</td>
<td style="text-align: right;">2.035</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td>Fringe (left)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">10</td>
</tr>
<tr class="even">
<td>Fringe (right)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">0.081</td>
<td style="text-align: right;">12</td>
</tr>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">6.0855</td>
<td style="text-align: right;">6.085</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="even">
<td>Fringe (bottom)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">6.0855</td>
<td style="text-align: right;">5.927</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td>Fringe (bottom)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">-0.1579</td>
<td style="text-align: right;">—</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="even">
<td>Fringe (left)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">2.4342</td>
<td style="text-align: right;">2.434</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="odd">
<td>Fringe (right)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">substrate</td>
<td style="text-align: center;">VSUBS</td>
<td style="text-align: right;">2.4342</td>
<td style="text-align: right;">2.434</td>
<td style="text-align: right;">20</td>
</tr>
</tbody>
</table>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p><code>MAGIC</code> handles shielding differently than <code>KPEX/2.5D</code>, it first assumes no shield exists, and later subtracts portions to arrive at the shielded value. That’s why the bold cells differ. Line 15 - 20 accumulate contributions, whereas line 34 subtracts a contribution:</p>
<ul>
<li>Line 15: <code>CapDebug (extNodeAreaFunc/Area) layer m1(97), net m1_10000_10000#,</code> <code>area=360000000 (9000 µm^2) nreg_cap += 232.02 fF</code></li>
<li>Line 17: <code>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer m1(97), net m1_10000_10000#,</code> <code>length=30000 (150 µm), nreg_cap += 6.0855 fF (now nreg_cap = 238.105 fF)</code></li>
<li>Line 18: <code>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer m1(97), net m1_10000_10000#,</code> <code>length=12000 (60 µm), nreg_cap += 2.4342 fF (now nreg_cap = 240.54 fF)</code></li>
<li>Line 19: <code>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer m1(97), net m1_10000_10000#,</code> <code>length=30000 (150 µm), nreg_cap += 6.0855 fF (now nreg_cap = 246.625 fF)</code></li>
<li>Line 20: <code>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer m1(97), net m1_10000_10000#,</code> <code>length=12000 (60 µm), nreg_cap += 2.4342 fF (now nreg_cap = 249.059 fF)</code></li>
<li>Line 34: <code>nreg_cap -= 0.157966 fF (now nreg_cap = 248.901 fF)</code></li>
</ul>
<p>Comparison:</p>
<ul>
<li><code>KPEX/2.5D</code>: <span class="math inline">\(4.86834 + 0.77242 + 0.2867 = 5.9275\)</span></li>
<li><code>MAGIC</code>: <span class="math inline">\(6.0855 - 0.157966 = 5.9275\)</span></li>
</ul>
</div>
</div>
<div id="cell-sideoverlap_simple_plates_li1_m1_-_fringe_li1_m1" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display" data-execution_count="10">
<div id="sideoverlap_simple_plates_li1_m1_-_fringe_li1_m1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sideoverlap_simple_plates_li1_m1_-_fringe_li1_m1-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Fringe capacitances li1 to m1.</figcaption>
</figure>
</div>
</div>
</div>
<div id="cell-sideoverlap_simple_plates_li1_m1_-_fringe_m1_li1" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display" data-execution_count="11">
<div id="sideoverlap_simple_plates_li1_m1_-_fringe_m1_li1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="doc_files/figure-html/sideoverlap_simple_plates_li1_m1_-_fringe_m1_li1-output-1.svg" class="img-fluid figure-img"></p>
<figcaption>Fringe capacitances m1 to li1.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<caption>Extracted Parasitic Fringe Capacitances between metals</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>Description</th>
<th style="text-align: right;">Layer Top</th>
<th style="text-align: left;">Net Top</th>
<th style="text-align: right;">Layer Bottom</th>
<th style="text-align: center;">Net Bottom</th>
<th style="text-align: right;">MAGIC [fF]</th>
<th style="text-align: right;">KPEX/2.5D [fF]</th>
<th style="text-align: right;">MAGIC Lines</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Fringe (top)</td>
<td style="text-align: right;">li1</td>
<td style="text-align: left;">li1</td>
<td style="text-align: right;">met1</td>
<td style="text-align: center;">met1</td>
<td style="text-align: right;">0.598</td>
<td style="text-align: right;">0.06</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td>Fringe (bottom)</td>
<td style="text-align: right;">met1</td>
<td style="text-align: left;">met1</td>
<td style="text-align: right;">li1</td>
<td style="text-align: center;">li1</td>
<td style="text-align: right;">0.0654</td>
<td style="text-align: right;">0.065</td>
<td style="text-align: right;">36</td>
</tr>
</tbody>
</table>
<div class="sourceCode" id="cb11"><pre class="sourceCode numberSource {csv} number-lines code-with-copy"><code class="sourceCode"><span id="cb11-1"><a href="#cb11-1"></a>Magic 8.3 revision 486 - Compiled on `date`.</span>
<span id="cb11-2"><a href="#cb11-2"></a></span>
<span id="cb11-3"><a href="#cb11-3"></a>----------------------------------------------------</span>
<span id="cb11-4"><a href="#cb11-4"></a></span>
<span id="cb11-5"><a href="#cb11-5"></a>Extracting sideoverlap_simple_plates_li1_m1 into /Users/martin/Source/klayout-pex/output_sky130A/sideoverlap_simple_plates_li1_m1__sideoverlap_simple_plates_li1_m1/magic_CC/sideoverlap_simple_plates_li1_m1.ext:</span>
<span id="cb11-6"><a href="#cb11-6"></a></span>
<span id="cb11-7"><a href="#cb11-7"></a>CapDebug (extNodeAreaFunc/Area) layer li(90), net li_34000_9000, area=4000000 (100 µm^2) nreg_cap += 3.699 fF</span>
<span id="cb11-8"><a href="#cb11-8"></a></span>
<span id="cb11-9"><a href="#cb11-9"></a>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer li(90), net li_34000_9000, length=10000 (50 µm), nreg_cap += 2.035 fF (now nreg_cap = 5.734 fF)</span>
<span id="cb11-10"><a href="#cb11-10"></a>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer li(90), net li_34000_9000, length=400 (2 µm), nreg_cap += 0.0814 fF (now nreg_cap = 5.8154 fF)</span>
<span id="cb11-11"><a href="#cb11-11"></a>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer li(90), net li_34000_9000, length=10000 (50 µm), nreg_cap += 2.035 fF (now nreg_cap = 7.8504 fF)</span>
<span id="cb11-12"><a href="#cb11-12"></a>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer li(90), net li_34000_9000, length=400 (2 µm), nreg_cap += 0.0814 fF (now nreg_cap = 7.9318 fF)</span>
<span id="cb11-13"><a href="#cb11-13"></a>CapDebug (extSetResist): li_34000_9000 area=4000000 (100 µm^2) perim=20800 (104 µm)</span>
<span id="cb11-14"><a href="#cb11-14"></a>CapDebug ---</span>
<span id="cb11-15"><a href="#cb11-15"></a>CapDebug (extNodeAreaFunc/Area) layer m1(97), net m1_10000_10000#, area=360000000 (9000 µm^2) nreg_cap += 232.02 fF</span>
<span id="cb11-16"><a href="#cb11-16"></a></span>
<span id="cb11-17"><a href="#cb11-17"></a>CapDebug (extNodeAreaFunc/Perimeter/TopSide) layer m1(97), net m1_10000_10000#, length=30000 (150 µm), nreg_cap += 6.0855 fF (now nreg_cap = 238.105 fF)</span>
<span id="cb11-18"><a href="#cb11-18"></a>CapDebug (extNodeAreaFunc/Perimeter/LeftSide) layer m1(97), net m1_10000_10000#, length=12000 (60 µm), nreg_cap += 2.4342 fF (now nreg_cap = 240.54 fF)</span>
<span id="cb11-19"><a href="#cb11-19"></a>CapDebug (extNodeAreaFunc/Perimeter/BottomSide) layer m1(97), net m1_10000_10000#, length=30000 (150 µm), nreg_cap += 6.0855 fF (now nreg_cap = 246.625 fF)</span>
<span id="cb11-20"><a href="#cb11-20"></a>CapDebug (extNodeAreaFunc/Perimeter/RightSide) layer m1(97), net m1_10000_10000#, length=12000 (60 µm), nreg_cap += 2.4342 fF (now nreg_cap = 249.059 fF)</span>
<span id="cb11-21"><a href="#cb11-21"></a>CapDebug (extSetResist): m1_10000_10000# area=360000000 (9000 µm^2) perim=84000 (420 µm)</span>
<span id="cb11-22"><a href="#cb11-22"></a>CapDebug ---</span>
<span id="cb11-23"><a href="#cb11-23"></a>CapDebug (extSideOverlapHalo): (li-m1) length=30.000000 µm, mult=0.011420, dnear=3.000000 µm (600), dfar=8.000000 µm (1600), snear=0.907713, sfar=0.965163 (cfrac=0.057450)</span>
<span id="cb11-24"><a href="#cb11-24"></a>CapDebug (extSideOverlapHalo) (li-substrate): mult=0.003699, snear=0.730477, sfar=0.893413 (sfrac=0.162935)</span>
<span id="cb11-25"><a href="#cb11-25"></a>CapDebug (extSideOverlapHalo): efflength=1.72351 µm, cap+=0.299029 aF, cap=59.8059 aF, e-&gt;ec_cap=0.1735, so_coupfrac=0, subfrac+=0, subfrac=0, so_subfrac=0</span>
<span id="cb11-26"><a href="#cb11-26"></a>CapDebug (sideoverlaphalo): met1-li1 += 0.059806 fF …   now met1-li1 == 0.059806 fF</span>
<span id="cb11-27"><a href="#cb11-27"></a>CapDebug ---</span>
<span id="cb11-28"><a href="#cb11-28"></a>CapDebug (extSideOverlapHalo): (m1-li) length=30.000000 µm, mult=0.011420, dnear=3.000000 µm (600), dfar=5.000000 µm (1000), snear=0.907713, sfar=0.944366 (cfrac=0.036653)</span>
<span id="cb11-29"><a href="#cb11-29"></a>CapDebug (extSideOverlapHalo) (m1-substrate): mult=0.002578, snear=0.634619, sfar=0.764408 (sfrac=0.129789)</span>
<span id="cb11-30"><a href="#cb11-30"></a>CapDebug (extSideOverlapHalo): efflength=1.0996 µm, cap+=0.327131 aF, cap=65.4263 aF, e-&gt;ec_cap=0.2975, so_coupfrac=0, subfrac+=0, subfrac=0, so_subfrac=0</span>
<span id="cb11-31"><a href="#cb11-31"></a>CapDebug (extSideOverlapHalo/obsolete_perimcap) layer m1(97), net met1, </span>
<span id="cb11-32"><a href="#cb11-32"></a>    efflength=3.89366 µm (778.733) = (sfrac(0.129789) - subfrac(0)) * length(30 µm)</span>
<span id="cb11-33"><a href="#cb11-33"></a>    exts_perimCap[m1][0] = 0.20285</span>
<span id="cb11-34"><a href="#cb11-34"></a>    nreg_cap -= 0.157966 fF (now nreg_cap = 248.901 fF)</span>
<span id="cb11-35"><a href="#cb11-35"></a>CapDebug (obsolete_perimcap): met1 -= 0.157966 fF … now met1 == 248.901423 fF</span>
<span id="cb11-36"><a href="#cb11-36"></a>CapDebug (sideoverlaphalo): met1-li1 += 0.065426 fF …   now met1-li1 == 0.125232 fF</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div style="page-break-after: always;"></div>
</section>
</section>
<section id="appendix" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Appendix</h1>
<section id="references" class="level2" data-number="8.1">




</section>
</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">8.1 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-fastfieldsolvers-fastercap-manual-chm" class="csl-entry" role="listitem">
Di Lorenzo, Enrico. 2019. <span>“FasterCap Embedded Help.”</span> 2019. <a href="https://www.fastfieldsolvers.com/Download/FasterCapHelp.chm">https://www.fastfieldsolvers.com/Download/FasterCapHelp.chm</a>.
</div>
<div id="ref-fastfieldsolvers-maxwell-capacitance-matrix" class="csl-entry" role="listitem">
———. 2023. <span>“The Maxwell Capacitance Matrix: White Paper WP110301. Revision 03.”</span> 2023. <a href="https://www.fastfieldsolvers.com/Papers/The_Maxwell_Capacitance_Matrix_WP110301_R03.pdf">https://www.fastfieldsolvers.com/Papers/The_Maxwell_Capacitance_Matrix_WP110301_R03.pdf</a>.
</div>
<div id="ref-edwards-2022-fsic-talk" class="csl-entry" role="listitem">
Edwards, R. Timothy. 2022. <span>“Whom Do You Trust? Validating Process Parameters for Open-Source Tools.”</span> <a href="https://wiki.f-si.org/index.php?title=Whom_do_you_trust%3F:_Validating_process_parameters_for_open-source_tools">https://wiki.f-si.org/index.php?title=Whom_do_you_trust%3F:_Validating_process_parameters_for_open-source_tools</a>.
</div>
<div id="ref-edwards-2023-chipsalliance-talk-slides" class="csl-entry" role="listitem">
———. 2023a. <span>“Full r-c Extraction in Magic (Presentation Slides).”</span> <a href="https://lists.chipsalliance.org/g/analog-wg/attachment/99/0/AWG_040423_Tim_Edwards_chips_alliance_slides.pdf">https://lists.chipsalliance.org/g/analog-wg/attachment/99/0/AWG_040423_Tim_Edwards_chips_alliance_slides.pdf</a>.
</div>
<div id="ref-edwards-2023-chipsalliance-talk-video" class="csl-entry" role="listitem">
———. 2023b. <span>“Full r-c Extraction in Magic (Presentation Video).”</span> <a href="https://www.youtube.com/watch?v=4d2mtiEHHeo">https://www.youtube.com/watch?v=4d2mtiEHHeo</a>.
</div>
<div id="ref-Maxwell_1873" class="csl-entry" role="listitem">
Maxwell, James Clerk. 1873. <em>A Treatise on Electricity and Magnetism</em>. Vol. 1. Clarendon Press.
</div>
<div id="ref-Nagel_1975" class="csl-entry" role="listitem">
Nagel, Laurence W. 1975. <span>“SPICE2: A Computer Program to Simulate Semiconductor Circuits.”</span> PhD thesis, EECS Department, University of California, Berkeley. <a href="http://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html">http://www2.eecs.berkeley.edu/Pubs/TechRpts/1975/9602.html</a>.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>Metal-Oxide-Metal capacitors<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>C++ generator scripts the built-in tech files are located in <code>cxx/gen_tech_pb/pdk/*.cpp</code>.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>To find the <code>site-packages</code> directory for the <code>klayout-pex</code> package, call <code>pip3 show klayout-pex</code>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Metal-Oxide-Metal capacitors<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Metal-Insulator-Metal capacitors<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>A fork of MAGIC which includes debug logging about the different parasitic contributions is hosted here: <a href="https://github.com/martinjankoehler/magic" class="uri">https://github.com/martinjankoehler/magic</a><a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div>Apache-2.0 license</div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/martinjankoehler\.github\.io\/klayout-pex-website\/");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>Website built with <a href="https://quarto.org/" class="external" target="_blank">Quarto</a> <br> <a href="https://github.com/martinjankoehler/klayout-pex-website" class="external" target="_blank">Code source</a></p>
</div>
  </div>
</footer>




</body></html>